import React from 'react';
import FetchJSONP from 'fetch-jsonp';
import {Spin,Alert,Pagination} from 'antd';
import MovieItem from './MovieItem.js';
export default class MovieList extends React.Component{
	constructor(props){
		super(props);
		this.state={
            movieType:props.match.params.types,
            nowPage:parseInt(props.match.params.start) || 1,
            pageSize:10,
            isLoading:true,
            movies:[],
            total:0
		}
	}

	componentWillMount(){
		console.log("commponentWillMount");
	}


	componentWillReceiveProps(newProps){
		console.log("componentWillReceiveProps");
		this.setState({
			movieType:newProps.match.params.types
		},()=>{
			this.apiLoadMovieList();
		})
	}


	shouldComponentUpdate(){
		console.log("shouldComponentUpdate");
		return true;
	}

	componentWillUpdate(){
		console.log("componentWillUpdate");
	}


	componentDidUpdate(){
		console.log('componnentDidUpdate');
	}


	componentWillUnmount(){
		console.log("componentWillUnmount");
	}


	componentDidMount(){
		console.log("commponentDidMount");
		this.apiLoadMovieList();
	}


	// 跳转到详情页
	handleNavigateToDetail=(id)=>{
		this.props.history.push(`/movie/detail/${id}`);
	}

	// 分页
	handlePageChange=(page)=>{
		this.setState({
			nowPage:page
		},()=>{
			this.apiLoadMovieList();
		})
	}

	// 加载数据
	apiLoadMovieList=()=>{
		// this.setState({
		// 	isLoading:true
		// });
		// const url = `https://douban.uieee.com/v2/movie/${this.state.movieType}?start=${this.state.nowPage}&count=${this.state.pageSize}`
		// FetchJSONP(url)
		// 	.then(response=>response.json())
		// 	.then(data=>{
		// 		this.setState({
		// 	isLoading:false,
		// 	total:data.total,
		// 	movies:data.subjects
		// })
		// 	})
		// 	.catch(ex=>console.log(ex))

        var data={
            "count":12,
            "start":0,
            "total":72,
            "subjects":[
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
        
                    ],
                    "title":"浪漫七夕之疯狂搅局",
                    "casts":[
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"张子晨",
                            "id":null
                        }
                    ],
                    "collect_count":8,
                    "original_title":"浪漫七夕之疯狂搅局",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"李琛",
                            "id":null
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541305621.jpg",
                        "large":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541305621.jpg",
                        "medium":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541305621.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/30391433/",
                    "id":"30391433"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "喜剧",
                        "动作",
                        "冒险"
                    ],
                    "title":"印度暴徒",
                    "casts":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1031931/",
                            "avatars":{
                                "small":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p13628.jpg",
                                "large":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p13628.jpg",
                                "medium":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p13628.jpg"
                            },
                            "name":"阿米尔·汗",
                            "id":"1031931"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1010569/",
                            "avatars":{
                                "small":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p53718.jpg",
                                "large":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p53718.jpg",
                                "medium":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p53718.jpg"
                            },
                            "name":"卡特莉娜·卡芙",
                            "id":"1010569"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1027845/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p9190.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p9190.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p9190.jpg"
                            },
                            "name":"阿米达普·巴强",
                            "id":"1027845"
                        }
                    ],
                    "collect_count":147,
                    "original_title":"Thugs of Hindostan",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1308426/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1495324131.21.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1495324131.21.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1495324131.21.jpg"
                            },
                            "name":"维贾伊·克利须那·阿查里雅",
                            "id":"1308426"
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541754700.jpg",
                        "large":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541754700.jpg",
                        "medium":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541754700.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/27019982/",
                    "id":"27019982"
                },
                {
                    "rating":{
                        "max":10,
                        "average":7,
                        "stars":"35",
                        "min":0
                    },
                    "genres":[
                        "剧情"
                    ],
                    "title":"神探狗笨吉",
                    "casts":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1358708/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/pkgttz5tui54cel_avatar_uploaded1464968611.11.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/pkgttz5tui54cel_avatar_uploaded1464968611.11.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/pkgttz5tui54cel_avatar_uploaded1464968611.11.jpg"
                            },
                            "name":"加布里埃尔·贝特曼",
                            "id":"1358708"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1369479/",
                            "avatars":{
                                "small":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1488088653.09.jpg",
                                "large":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1488088653.09.jpg",
                                "medium":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1488088653.09.jpg"
                            },
                            "name":"达比·坎普",
                            "id":"1369479"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1027256/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p19702.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p19702.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p19702.jpg"
                            },
                            "name":"基拉·桑切斯",
                            "id":"1027256"
                        }
                    ],
                    "collect_count":1422,
                    "original_title":"Benji",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1369948/",
                            "avatars":{
                                "small":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1522748236.29.jpg",
                                "large":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1522748236.29.jpg",
                                "medium":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1522748236.29.jpg"
                            },
                            "name":"布兰登·坎普",
                            "id":"1369948"
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541725145.jpg",
                        "large":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541725145.jpg",
                        "medium":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541725145.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/26895438/",
                    "id":"26895438"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "剧情"
                    ],
                    "title":"阳光星旅团",
                    "casts":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1334215/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1473682330.23.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1473682330.23.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1473682330.23.jpg"
                            },
                            "name":"苏小妹",
                            "id":"1334215"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1399296/",
                            "avatars":{
                                "small":"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                                "large":"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                                "medium":"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                            },
                            "name":"蔡佳妤",
                            "id":"1399296"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1399297/",
                            "avatars":{
                                "small":"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                                "large":"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                                "medium":"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                            },
                            "name":"米拉",
                            "id":"1399297"
                        }
                    ],
                    "collect_count":9,
                    "original_title":"阳光星旅团",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1348348/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1426075763.73.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1426075763.73.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1426075763.73.jpg"
                            },
                            "name":"刘凌",
                            "id":"1348348"
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2529364129.jpg",
                        "large":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2529364129.jpg",
                        "medium":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2529364129.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/30285934/",
                    "id":"30285934"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "喜剧",
                        "冒险"
                    ],
                    "title":"断片之险途夺宝",
                    "casts":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1000905/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p46.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p46.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p46.jpg"
                            },
                            "name":"葛优",
                            "id":"1000905"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1317663/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p40756.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p40756.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p40756.jpg"
                            },
                            "name":"岳云鹏",
                            "id":"1317663"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1016663/",
                            "avatars":{
                                "small":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1536658358.18.jpg",
                                "large":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1536658358.18.jpg",
                                "medium":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1536658358.18.jpg"
                            },
                            "name":"杜淳",
                            "id":"1016663"
                        }
                    ],
                    "collect_count":1215,
                    "original_title":"断片之险途夺宝",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1324612/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/pbYO4zDByocwcel_avatar_uploaded1352024636.33.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/pbYO4zDByocwcel_avatar_uploaded1352024636.33.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/pbYO4zDByocwcel_avatar_uploaded1352024636.33.jpg"
                            },
                            "name":"罗登",
                            "id":"1324612"
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541553709.jpg",
                        "large":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541553709.jpg",
                        "medium":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541553709.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/26882457/",
                    "id":"26882457"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "动作",
                        "奇幻",
                        "冒险"
                    ],
                    "title":"云南虫谷",
                    "casts":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1318565/",
                            "avatars":{
                                "small":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p43387.jpg",
                                "large":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p43387.jpg",
                                "medium":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p43387.jpg"
                            },
                            "name":"蔡珩",
                            "id":"1318565"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1316959/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1538706988.45.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1538706988.45.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1538706988.45.jpg"
                            },
                            "name":"顾璇",
                            "id":"1316959"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1363813/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1477461192.41.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1477461192.41.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1477461192.41.jpg"
                            },
                            "name":"于恒",
                            "id":"1363813"
                        }
                    ],
                    "collect_count":102,
                    "original_title":"云南虫谷",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1320824/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543204019.02.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543204019.02.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543204019.02.jpg"
                            },
                            "name":"非行",
                            "id":"1320824"
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2542212636.jpg",
                        "large":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2542212636.jpg",
                        "medium":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2542212636.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/26744597/",
                    "id":"26744597"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "剧情",
                        "喜剧"
                    ],
                    "title":"来电狂响",
                    "casts":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1009179/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542346320.44.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542346320.44.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542346320.44.jpg"
                            },
                            "name":"佟大为",
                            "id":"1009179"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1319032/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1444800807.11.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1444800807.11.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1444800807.11.jpg"
                            },
                            "name":"马丽",
                            "id":"1319032"
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1000145/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p2520.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p2520.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p2520.jpg"
                            },
                            "name":"霍思燕",
                            "id":"1000145"
                        }
                    ],
                    "collect_count":98,
                    "original_title":"来电狂响",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1321152/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1483685290.54.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1483685290.54.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1483685290.54.jpg"
                            },
                            "name":"于淼",
                            "id":"1321152"
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2542268337.jpg",
                        "large":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2542268337.jpg",
                        "medium":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2542268337.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/30377703/",
                    "id":"30377703"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "恐怖"
                    ],
                    "title":"午夜废墟",
                    "casts":[
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"张圣岳",
                            "id":null
                        },
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"常奕然",
                            "id":null
                        },
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"刘俊峰",
                            "id":null
                        }
                    ],
                    "collect_count":4,
                    "original_title":"午夜废墟",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"胡韵",
                            "id":null
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541306508.jpg",
                        "large":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541306508.jpg",
                        "medium":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541306508.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/30391458/",
                    "id":"30391458"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "儿童",
                        "动画",
                        "冒险"
                    ],
                    "title":"两只小猪之勇闯神秘岛",
                    "casts":[
        
                    ],
                    "collect_count":13,
                    "original_title":"两只小猪之勇闯神秘岛",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1398710/",
                            "avatars":{
                                "small":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1533614047.18.jpg",
                                "large":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1533614047.18.jpg",
                                "medium":"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1533614047.18.jpg"
                            },
                            "name":"罗红胜",
                            "id":"1398710"
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2530155986.jpg",
                        "large":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2530155986.jpg",
                        "medium":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2530155986.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/30292587/",
                    "id":"30292587"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "动画",
                        "冒险"
                    ],
                    "title":"警车联盟",
                    "casts":[
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"朱祎",
                            "id":null
                        },
                        {
                            "alt":"https://movie.douban.com/celebrity/1348154/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1538873069.54.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1538873069.54.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1538873069.54.jpg"
                            },
                            "name":"杨慧紫",
                            "id":"1348154"
                        },
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"楚衔",
                            "id":null
                        }
                    ],
                    "collect_count":37,
                    "original_title":"警车联盟",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"邓志基",
                            "id":null
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2542479198.jpg",
                        "large":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2542479198.jpg",
                        "medium":"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2542479198.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/27097866/",
                    "id":"27097866"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "喜剧",
                        "动画",
                        "冒险"
                    ],
                    "title":"阿里巴巴三根金发",
                    "casts":[
        
                    ],
                    "collect_count":11,
                    "original_title":"阿里巴巴三根金发",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":"https://movie.douban.com/celebrity/1361983/",
                            "avatars":{
                                "small":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1505789251.02.jpg",
                                "large":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1505789251.02.jpg",
                                "medium":"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1505789251.02.jpg"
                            },
                            "name":"蒋叶峰",
                            "id":"1361983"
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541193624.jpg",
                        "large":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541193624.jpg",
                        "medium":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541193624.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/30176069/",
                    "id":"30176069"
                },
                {
                    "rating":{
                        "max":10,
                        "average":0,
                        "stars":"00",
                        "min":0
                    },
                    "genres":[
                        "喜剧",
                        "动画",
                        "冒险"
                    ],
                    "title":"龟兔大作战",
                    "casts":[
        
                    ],
                    "collect_count":2,
                    "original_title":"龟兔大作战",
                    "subtype":"movie",
                    "directors":[
                        {
                            "alt":null,
                            "avatars":null,
                            "name":"代长浩",
                            "id":null
                        }
                    ],
                    "year":"2018",
                    "images":{
                        "small":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541109672.jpg",
                        "large":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541109672.jpg",
                        "medium":"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541109672.jpg"
                    },
                    "alt":"https://movie.douban.com/subject/30387308/",
                    "id":"30387308"
                }
            ],
            "title":"即将上映的电影"
        };
        
		console.log(data);

		this.setState({
			isLoading:false,
			total:data.total,
			movies:data.subjects
		});
	}

	render(){
		if(this.state.isLoading){
            return  <Spin tip="Loading...">
            <Alert
              message="正在加载电影列表"
              description="已完成97%，即将渲染"
              type="info"
            />
          </Spin>
        }else{
        	 return <React.Fragment>
	            <div style={{display:'flex',justifyContent:'space-around',flexWrap:'wrap',background:'#eee'}}>
	                {this.state.movies.map((item,index)=>{
	                    return <div style={{width:'170px'}} key={index} onClick={()=>this.handleNavigateToDetail(item.id)}>
	                         <MovieItem {...item}></MovieItem>
	                    </div>
	                })}
	            </div>
	            <Pagination current={this.state.nowPage} onChange={this.handlePageChange} total={this.state.total/this.state.pageSize*10} />        
            </React.Fragment>
        }
	}
}